name: aula_01
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #FIREBASE PLUGINS
  #firebase: ^9.0.1
  firebase_core: ^1.4.0
  firebase_dynamic_links: ^0.8.0
  firebase_auth: 1.0.0
  firebase_analytics: ^8.3.0
  firebase_crashlytics: ^2.0.0
  cloud_firestore: ^2.5.1
  firebase_storage: 8.0.0
  firebase_database: ^6.1.0
  firebase_messaging: ^10.0.6


  #FIM FIREBASE PLUGINS

  rxdart: ^0.26.0
  syncfusion_officechart: ^19.2.59-beta
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/